package Trwalosc;
// Generated 2024-02-18 02:24:32 by Hibernate Tools 4.3.1



/**
 * Hats generated by hbm2java
 */
public class Hats  implements java.io.Serializable {


     private short hatId;
     private String brand;
     private String material;
     private String type;
     private String styleColor;
     private Boolean hasBrim;
     private Boolean hasRim;

    public Hats() {
    }

	
    public Hats(short hatId) {
        this.hatId = hatId;
    }
    public Hats(short hatId, String brand, String material, String type, String styleColor, Boolean hasBrim, Boolean hasRim) {
       this.hatId = hatId;
       this.brand = brand;
       this.material = material;
       this.type = type;
       this.styleColor = styleColor;
       this.hasBrim = hasBrim;
       this.hasRim = hasRim;
    }
   
    public short getHatId() {
        return this.hatId;
    }
    
    public void setHatId(short hatId) {
        this.hatId = hatId;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getMaterial() {
        return this.material;
    }
    
    public void setMaterial(String material) {
        this.material = material;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStyleColor() {
        return this.styleColor;
    }
    
    public void setStyleColor(String styleColor) {
        this.styleColor = styleColor;
    }
    public Boolean getHasBrim() {
        return this.hasBrim;
    }
    
    public void setHasBrim(Boolean hasBrim) {
        this.hasBrim = hasBrim;
    }
    public Boolean getHasRim() {
        return this.hasRim;
    }
    
    public void setHasRim(Boolean hasRim) {
        this.hasRim = hasRim;
    }




}


